version: '1.0'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8080:80"
    restart: always
    
  openidconnectintegrationexample:
    image: backend
    build:
      context: .
      dockerfile: OpenIdConnectIntegrationExample/Dockerfile
    ports:
      - "8081:80"
    restart: always