// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenIdConnectIntegrationExample.Database;

#nullable disable

namespace OpenIdConnectIntegrationExample.Database.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20230817150954_CertificatesAndClientSecretAndWebKey")]
    partial class CertificatesAndClientSecretAndWebKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("OpenIdConnectIntegrationExample.Models.OIDCConfiguration", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("audience")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("authority")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("callback_uri")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("certificatePassword")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("certificateSerial")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("client_id")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("client_secret")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("jsonWebKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("redirect_uri")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("response_type")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("scope")
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("OIDCConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
